name: Jira Update Summary
description: Update fields of a specific JIRA Issue
branding:
  icon: 'chevron-right'
  color: 'blue'
inputs:
  issue:
    description: Key of the issue to be transitioned
    required: true
  summary:
    description: Version to update the JIRA summary field
    required: true
runs:
  using: 'node12'
  main: './dist/index.js'
